name: Item of Interest (IOI)
description: You found some interesting Algorand blockchain activity and want to share / investigate
labels: ["ioi"]
body:
  - type: dropdown
    id: network
    attributes:
      label: Which Algorand network?
      multiple: true
      options:
        - mainnet
        - testnet
        - betanet
        - other
  - type: textarea
    id: ioi
    attributes:
      label: Share your IOI
      description: Share details like keys (accounts, asset IDs, app IDs) and what you know
    validations:
      required: true